config/routes.rb
RUMTestRubyApp::Application.routes.draw do
  resources :rums

end

app/models/rum.rb
class Rum < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/rums_controller.rb
class RumsController < ApplicationController
  # GET /rums
  # GET /rums.json
  def index
    @rums = Rum.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rums }
    end
  end
  
  layout :choose_layout
  
  # GET /rums/1
  # GET /rums/1.json
  def show
    @rum = Rum.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rum }
    end
  end

  # GET /rums/new
  # GET /rums/new.json
  def new
    @rum = Rum.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rum }
    end
  end

  # GET /rums/1/edit
  def edit
    @rum = Rum.find(params[:id])
  end

  # POST /rums
  # POST /rums.json
  def create
    @rum = Rum.new(params[:rum])

    respond_to do |format|
      if @rum.save
        format.html { redirect_to @rum, notice: 'Rum was successfully created.' }
        format.json { render json: @rum, status: :created, location: @rum }
      else
        format.html { render action: "new" }
        format.json { render json: @rum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rums/1
  # PUT /rums/1.json
  def update
    @rum = Rum.find(params[:id])

    respond_to do |format|
      if @rum.update_attributes(params[:rum])
        format.html { redirect_to @rum, notice: 'Rum was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @rum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rums/1
  # DELETE /rums/1.json
  def destroy
    @rum = Rum.find(params[:id])
    @rum.destroy

    respond_to do |format|
      format.html { redirect_to rums_url }
      format.json { head :ok }
    end
  end
  
  private
  def choose_layout
    unless ['index', 'new','create', 'destroy', 'edit'].include? action_name
      "testcase_#{@rum.id}"
    else
      "application"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rums_helper.rb
module RumsHelper
end

app/views/layouts/_footer.html.erb
<footer>

<li><%= link_to 'Home Page', rums_path %> </li>
<%= NewRelic::Agent.browser_timing_footer rescue "" %>

</footer>

app/views/layouts/_footer_testcase_3.html.erb
<footer>
<%= NewRelic::Agent.browser_timing_footer rescue "" %>

<li><%= link_to 'Home Page', rums_path %> </li>

</footer>

app/views/layouts/_footer_testcase_8.html.erb
<footer>

<li><%= link_to 'Home Page', rums_path %> </li>
<%= NewRelic::Agent.browser_timing_footer rescue "" %>


</footer>

app/views/layouts/_footer_testcase_9.html.erb
<footer>
  

<li><%= link_to 'Home Page', rums_path %> </li>
<%= NewRelic::Agent.browser_timing_footer rescue "" %>


</footer>

app/views/layouts/_header.html.erb
<header>
  <%= NewRelic::Agent.browser_timing_header rescue "" %>
  <div id="logo">
    <%= image_tag 'rum.jpeg' %>
  </div>
  <meta http-equiv="content-type" content="text/html;charset=ISO_8859-1" />



</header>

app/views/layouts/_header_testcase_1.html.erb
<header>

  <%= image_tag 'lightrum.jpeg' %>
  <title> This is test case 1 </title>
<style type= "text/css">
h1 {color:red;}
p {color:blue}
</style>
<meta name="description" content="Taste Rum" />


</header>

app/views/layouts/_header_testcase_2.html.erb
<header>
  <%= image_tag 'goldrum.jpeg' %>
  <meta name="keywords" content="HTML,CSS,XML,JavaScript" 
<%= NewRelic::Agent.browser_timing_header rescue "" %>
</header>

app/views/layouts/_header_testcase_3.html.erb
<header>
<%= NewRelic::Agent.browser_timing_header rescue "" %>

<%= image_tag 'spicedrum.jpeg'%>
<meta name="author" content="Mei Xue" />


</header>

app/views/layouts/_header_testcase_4.html.erb
<header>
  <%= NewRelic::Agent.browser_timing_header rescue "" %>

  <%= image_tag 'darkrum.jpeg' %>
 <meta http-equiv="content-type" content="text/html;charset=UTF-8" />


</header>

app/views/layouts/_header_testcase_8.html.erb
<header>
  <%= NewRelic::Agent.browser_timing_header rescue "" %>

  <div id="logo">
    <%= image_tag 'housemaderum.jpeg' %>
  </div>
  <%= NewRelic::Agent.browser_timing_header rescue "" %>




</header>

app/views/layouts/_header_testcase_9.html.erb
<header>
<%= NewRelic::Agent.browser_timing_header rescue "" %>

  <title> This is test case 9 </title>
<style type= "text/css">
h1 {color:purple;}
p {color:green}
</style>



</header>

app/views/layouts/testcase_2.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RUMTestRubyApp</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1> Taste Gold Rum </h1>

<%= render 'layouts/header_testcase_2'%>

<%= yield %>

<%= render 'layouts/footer_testcase_2'%>

</body>
</html>

app/views/layouts/testcase_4.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RUMTestRubyApp</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1> Taste Dark Rum </h1>
  <h2> 深色朗姆酒 </h2>

<%= render 'layouts/header_testcase_4'%>

<%= yield %>

<%= render 'layouts/footer_testcase_4'%>

</body>
</html>

app/views/layouts/testcase_7.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RUMTestRubyApp</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1> Taste Premium Rum </h1>

<%= render 'layouts/header_testcase_7'%>

<%= yield %>

<%= render 'layouts/footer_testcase_7'%>

</body>
</html>

app/views/rums/_form.html.erb
<%= form_for(@rum) do |f| %>
  <% if @rum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rum.errors.count, "error") %> prohibited this rum from being saved:</h2>

      <ul>
      <% @rum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rums/edit.html.erb
<h1>Editing rum</h1>

<%= render 'form' %>

<%= link_to 'Show', @rum %> |
<%= link_to 'Back', rums_path %>

app/views/rums/index.html.erb
<h1>Welcome to Rum Taste Ruby Web</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rums.each do |rum| %>
  <tr>
    <td><%= rum.name %></td>
    <td><%= rum.price %></td>
    <td><%= link_to rum.name, rum %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Rum', new_rum_path %>

app/views/rums/new.html.erb
<h1>New rum</h1>

<%= render 'form' %>

<%= link_to 'Back', rums_path %>

app/views/rums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @rum.name %>
</p>

<p>
  <b>Price:</b>
  <%= @rum.price %>
</p>


<%= link_to 'Edit', edit_rum_path(@rum) %> |
<%= link_to 'Back', rums_path %>